name: urwaypayment
description: This Flutter plugin provide merchants to easy and hasslefree integration with Urway Payment gateway API's.
version: 2.0.6
homepage: https://github.com/URWAYios/Flutter_Plugin.git

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  convert: ^3.1.2
  crypto: ^3.0.6
  connectivity_plus: ^6.1.3

  device_info_plus: ^11.3.3
  dart_ipify: ^1.1.1

  apple_pay_flutter: ^1.0.3
  package_info_plus: ^8.3.0
  webview_flutter: ^4.10.0
  #webview_flutter_android: ^3.16.3


dependency_overrides:


# The following section is specific to Flutter.
flutter:
