name: urwaypayment
description: This Flutter plugin provide merchants to easy and hasslefree integration with Urway Payment gateway API's.
version: 2.0.3
homepage: https://github.com/URWAYios/Flutter_Plugin.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0


  convert: ^3.0.0
  crypto: ^3.0.3
  connectivity_plus: ^5.0.1
  email_validator: ^2.0.1
  device_info_plus: ^9.1.0
  dart_ipify: ^1.1.1
  apple_pay_flutter: ^1.0.2

  package_info_plus: ^8.0.0
  webview_flutter: ^4.8.0
  #webview_flutter_android: ^3.16.3


dependency_overrides:


# The following section is specific to Flutter.
flutter:
