name: urwaypayment
description: This Flutter plugin provide merchants to easy and hasslefree integration with Urway Payment gateway API's.
version: 1.0.3
homepage: https://github.com/URWAYios/Flutter_Plugin.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  permission_handler: ^9.0.1
  path_provider: ^2.0.1
  flutter_inappwebview: ^5.3.2
  convert: ^3.0.0
  crypto: ^3.0.1
  connectivity: ^3.0.6
  email_validator: ^2.0.1
  connectivity_macos: ^0.2.1+2
  device_info_plus: ^4.1.2
  dart_ipify: ^1.1.1
  apple_pay_flutter: ^0.0.8
  package_info_plus: ^1.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

