name: urwaypayment
description: This Flutter plugin provide merchants to easy and hasslefree integration with Urway Payment gateway API's.
version: 1.0.11
homepage: https://github.com/URWAYios/Flutter_Plugin.git

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  convert: ^3.1.1
  crypto: ^3.0.3
  connectivity_plus: ^4.0.1
  email_validator: ^2.1.17
  device_info_plus: ^9.0.2
  dart_ipify: ^1.1.1
  apple_pay_flutter: ^0.0.8
  package_info_plus: ^4.0.2
  webview_flutter_plus: ^0.2.0
#  webview_flutter_plus: ^0.3.0+2







# The following section is specific to Flutter.
flutter:

